
name: Universal Jar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        # run: ./gradlew build
        run: ./gradlew :abcdecoder:packageReleaseUberJarForCurrentOS -Puniversal

      - name: Upload GitHub Actions artifact of gradle build
        uses: actions/upload-artifact@v4
        with:
          name: universal-jar
          path: ${{ github.workspace }}/abcdecoder/build/compose/jars/*.jar
